/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as ContextRouteImport } from './routes/context'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MediaRouteImport } from './routes/media'
import { Route as OutputsRouteImport } from './routes/outputs'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as SystemRouteImport } from './routes/system'
import { Route as WorkRouteImport } from './routes/work'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiIntakeRouteImport } from './routes/api/intake'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiBlobIdRouteImport } from './routes/api/blob.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ContextRoute = ContextRouteImport.update({
  id: '/context',
  path: '/context',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const OutputsRoute = OutputsRouteImport.update({
  id: '/outputs',
  path: '/outputs',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntakeRoute = ApiIntakeRouteImport.update({
  id: '/api/intake',
  path: '/api/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlobIdRoute = ApiBlobIdRouteImport.update({
  id: '/api/blob/$id',
  path: '/api/blob/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/context': typeof ContextRoute
  '/documents': typeof DocumentsRoute
  '/intake': typeof IntakeRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/outputs': typeof OutputsRoute
  '/review': typeof ReviewRoute
  '/system': typeof SystemRoute
  '/work': typeof WorkRoute
  '/api/health': typeof ApiHealthRoute
  '/api/intake': typeof ApiIntakeRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blob/$id': typeof ApiBlobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/context': typeof ContextRoute
  '/documents': typeof DocumentsRoute
  '/intake': typeof IntakeRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/outputs': typeof OutputsRoute
  '/review': typeof ReviewRoute
  '/system': typeof SystemRoute
  '/work': typeof WorkRoute
  '/api/health': typeof ApiHealthRoute
  '/api/intake': typeof ApiIntakeRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blob/$id': typeof ApiBlobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/context': typeof ContextRoute
  '/documents': typeof DocumentsRoute
  '/intake': typeof IntakeRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/outputs': typeof OutputsRoute
  '/review': typeof ReviewRoute
  '/system': typeof SystemRoute
  '/work': typeof WorkRoute
  '/api/health': typeof ApiHealthRoute
  '/api/intake': typeof ApiIntakeRoute
  '/api/mcp': typeof ApiMcpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blob/$id': typeof ApiBlobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/context'
    | '/documents'
    | '/intake'
    | '/login'
    | '/media'
    | '/outputs'
    | '/review'
    | '/system'
    | '/work'
    | '/api/health'
    | '/api/intake'
    | '/api/mcp'
    | '/api/auth/$'
    | '/api/blob/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/context'
    | '/documents'
    | '/intake'
    | '/login'
    | '/media'
    | '/outputs'
    | '/review'
    | '/system'
    | '/work'
    | '/api/health'
    | '/api/intake'
    | '/api/mcp'
    | '/api/auth/$'
    | '/api/blob/$id'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/context'
    | '/documents'
    | '/intake'
    | '/login'
    | '/media'
    | '/outputs'
    | '/review'
    | '/system'
    | '/work'
    | '/api/health'
    | '/api/intake'
    | '/api/mcp'
    | '/api/auth/$'
    | '/api/blob/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  ContextRoute: typeof ContextRoute
  DocumentsRoute: typeof DocumentsRoute
  IntakeRoute: typeof IntakeRoute
  LoginRoute: typeof LoginRoute
  MediaRoute: typeof MediaRoute
  OutputsRoute: typeof OutputsRoute
  ReviewRoute: typeof ReviewRoute
  SystemRoute: typeof SystemRoute
  WorkRoute: typeof WorkRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiIntakeRoute: typeof ApiIntakeRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBlobIdRoute: typeof ApiBlobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/context': {
      id: '/context'
      path: '/context'
      fullPath: '/context'
      preLoaderRoute: typeof ContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outputs': {
      id: '/outputs'
      path: '/outputs'
      fullPath: '/outputs'
      preLoaderRoute: typeof OutputsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/intake': {
      id: '/api/intake'
      path: '/api/intake'
      fullPath: '/api/intake'
      preLoaderRoute: typeof ApiIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blob/$id': {
      id: '/api/blob/$id'
      path: '/api/blob/$id'
      fullPath: '/api/blob/$id'
      preLoaderRoute: typeof ApiBlobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  ContextRoute: ContextRoute,
  DocumentsRoute: DocumentsRoute,
  IntakeRoute: IntakeRoute,
  LoginRoute: LoginRoute,
  MediaRoute: MediaRoute,
  OutputsRoute: OutputsRoute,
  ReviewRoute: ReviewRoute,
  SystemRoute: SystemRoute,
  WorkRoute: WorkRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiIntakeRoute: ApiIntakeRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBlobIdRoute: ApiBlobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
